language: node_js

node_js: node

script:
 - npm run nearley
 - npm run tsc
 - npm test
 - npm run coveralls

deploy:
  provider: npm
  email: rob@calculem.us
  skip_cleanup: true
  api_key:
    secure: TZE6j6n7fgLTLa5SSUcmFotLGwc0GmFMCUZmhDJhKaB28jdVRv6QSoJxasjaVT4SMfROO096/Qg7jzTxi1JJ7mPZ9+ixUyIJJZSeGkGHVoGXu12+v5Mji18iLMPxnXhFbZE7HsNSHXNG1sG7Zp4EHAarqK6hU4etwlFZILUGdspGGKjpN4lBCbbElIi0MQ1s4k70KWHDHG45tNKUHllCM6njkjwikaOAHviQ575SzgYoIfnuOOSypNA1HE7b+XuCunU9VZLruwjQi4gg0NWHhIFNv21FpACYOilyIKgXSUgUi+b0vPYShgyMqulK7Z6VzNQRbxzKhOHrkPhWA5u1uEy4+uEj6ZVqJrxwekPOL676d5J08Y2qgHrpT+XheVe3LRMw5ywsJTyT9Z14TgAKcI4xKkmZJfNxFhRbFUDf4gxtRoaKXI7aqRXESO2NfVaIPKa2h8S4SEAuNV1Zh/Pttu6teKV8/iGMefwfDQQuQLtcAGbrOLuBVzr0JznWijKWtP8YqTayK6XqJ1SCyrUAAI99R4O3LvNyCFV/vKHnPd1oMqHQ5kcsGHxQl1QPh8YQCRksV2wKYMmrtLXcdGW/rLlP7pTZ/dqtr4wUFkrbJTqV39XP3XxXPdVgUfOPIVV1nV54y0YFyVoeqIOhqJZED8JzYGMa+ggejY+E1GSjbms=
  on:
    repo: avocado-productions/tutch
    branch: master
