language: node_js

node_js: node

script:
- npm run nearley
- npm run tsc
- npm test
- npm run coveralls

deploy:
  provider: npm
  email: rob@calculem.us
  skip-cleanup: true
  api_key:
    secure: uAeCpmH14HmbXVkcs39/qLe24FBoQACE1VJkSD1PmpAwRqtmYt6EbFtl4wIdVz1GVjJxmYvzwDSTA9DcrvSf8KqASn3AjWrSd67f9yoNNQQRCDM2edO6CQ9rcCfaWRprCo4xat8cWuvjj3yKGx0ht9QWt11+dySpycVAStYdIeTDyZ2JDStVCrGTIxzKSdsfiEf7IUTI0HioklW0l0152cXg39GPeqSjxhYPzAGmvfhetipZ9oZK9V95tTtFqIoy+NUR5sb4izBrWI1r+OhHYn9XSVueY/HV+EPGjl+3A2akgcgfHtUsFow3/mInzoTVhzqRYIvA3m/aYEkT9X4DjJwSTDbKx0Jw4+80frn0KCkMVf8h+WohkMLbxcUFJbmiKlP+iYfCzJFrW6EWIaYAE10kUM5WknWFxaRcN8aHE7iRo5+rW8ECxjiUpb8cG13RU/udxxUhFJX7ax+i5vKgmVH1CSlBX0caSiLjSf/YtexoD7Fz/GimCKWnv/t8X/BvGth2z4uBsBARPQAPSkwC6zlJ63BKbpin3oilJCPIikHn1Iri4dq65s9q61UsnnzQBclwH33zEe83KRiilzIyRlNS3TOLn9mZwypXhlAHLr8n8OeRmGextn2TiPBDt6BubXh3m7htTIBsqH6dUaGv1VLYy2JXCH/PsQ5PYUGE9bY=
  on:
    repo: retutch/tutch
    branch: master
